version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3307"
    volumes:
      - valter_data:/var/lib/mysql

volumes:
  valter_data: